### ISSUE TITLE
EEPROM not working correctly

### ISSUE THREAD

**Issue by robotalec** [nicolacimmino/PLC-14500#10]
I have been trying to figure this out but I have been having an issue with my REV.b board(pre and post modified to work for rev.c) where I cannot flash the eeprom. When i run the tools it runs correctly and I am sending to the right com but nothing changes on the board after restarting. I used a simple Arduino code to print all the eeprom and it shows nothing was uploaded. I thought it might be a bad nano so I tired uploading to a spare nano i had and its eeprom is blank as well. I have tried both rev b and rev c asm examples but nothing seems to load.

**Comment by nicolacimmino** [comment]
Hi,

Can you make sure the 14500Mon is flashed on the Arduino before sending a bin file using the tools? The latest version is here in this repo under : https://github.com/nicolacimmino/PLC-14500/blob/master/14500mon/

You could also try to open a terminal connection to the COM port (9600,n,8,1) and use the monitor to dump the current program in EEPROM (see diasassemble and dump commands here: https://github.com/nicolacimmino/PLC-14500/tree/master/14500mon )

Let me know of any findings.

Regards,
Nicola
