### ISSUE TITLE
missing tools/assembler/bin\assembler.dart

### ISSUE THREAD

**Issue by zoul0813** [nicolacimmino/PLC-14500#18]
It looks like `[Bb]in/` is in the `.gitignore`, and the `tools/assembler/bin\assembler.dart` file referenced in `build_releases.cmd` is not available.

I'm attempting to make a MacOS build, but can not generate the assembler due to the missing assembler.dart

Admittedly, I'm not very familiar with Dart, and could be doing something wrong... 

I've duplicated all the `.cmd` files, and converted them into MacOS friendly `.sh` files (and can provide this as a PR once I get it working - with linux compatibility included)

**Comment by nicolacimmino** [comment]
Thanks for pointing this out! I have fixed and added the file.

If you manage to get a working version for the Mac that would be great, I don't have one around to test.

**Comment by zoul0813** [comment]
@nicolacimmino thanks - looks like I managed to get a working build on my Mac, but after further review of the tools/assembler/README.md, I noticed it mentions an assembler-cc65 option, and links to that folder ... but that folder is also not supplied in the repo.

To test the Mac build of the assembler, I assembled the tools/simulator/examples/test_program_a.asm with it ... the resulting binary I got was 256B in size, compared to the original 13B bin that was in the folder (I also had to add the .board directive to the top - perhaps the assembler should assume the `PLC14500-Nano` unless specified?).

My newly compiled test_program_a.bin, at 256B, also appears to have set all the zeros to `0x0F` ... where the original bin had a trailing 0, mine has trailing `0x0F` up to 256B

Not sure if this is due to changes in the assembler, made after the test_program_a.bin was last compiled for the simulator?

**Comment by nicolacimmino** [comment]
Thanks for pointing that out! The CC65 stuff was moved to another repo to avoid generting too much confusion, I have fixed the read.me link to point to that repo instead of the old folder.

Regarding the binaries that's exactly what the current bootloader expects: 256-byte files padded with 0x0F (which is a NOPF, so no side effects if you forget a JMP 0 at the end of your program).

I like to have the board directive mandatory so that it's always clear for what board to build, true that at the moment there is only the nano, but I have plans to develop others.

**Comment by zoul0813** [comment]
@nicolacimmino PR #21 should close this issue, and provides a build_releases.sh that works on my Apple Silicon Mac

I also provided a link to the Dart Install, which is what I followed to get Dart setup on my system.

I haven't tried the cc65 stuff yet... will let you know when I do

Apologies for the delay in getting this PR in ... I got sidetracked

**Comment by nicolacimmino** [comment]
@zoul0813  thanks for the PR! I merged it. In fact someone just in these days asked me about running the assembler on a Mac.
